name: mryr
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.1.1+23

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  flutter_svg: ^0.18.1
  http: ^0.12.2
  intl: ^0.16.1 #DateTime Parsing
  badges: ^1.1.1 #알림에 사용할 Badge
  percent_indicator: "^2.1.5" #퍼센테이지 바
  flutter_datetime_picker: ^1.4.0 #날짜 받아오기 위함
  provider: ^4.3.2+3 #provider
  firebase_messaging: ^6.0.16
  firebase_auth: ^0.18.3
  # adhara_socket_io: ^0.4.2
  sqflite: ^1.3.1
  path: ^1.7.0
  path_provider: ^1.6.11
  page_transition: ^1.1.6
  flutter_local_notifications: ^1.4.4+4
  vibration: ^1.4.0
  image_picker: ^0.6.7+7
  http_parser: ^3.1.4
  async: ^2.4.2
  flutter_native_image: ^0.0.5+2
  image: ^2.1.11
  flutter_statusbarcolor: ^0.2.3
  date_range_picker: ^1.0.6
  splashscreen: ^1.2.0
  animated_splash_screen: ^1.0.0
  webview_flutter: ^1.0.7
  #구글 지도 api
  google_maps_flutter: ^1.2.0 #^1.0.3
  flutter_form_builder:
    git:
      url: git://github.com/ryanhz/flutter_form_builder.git
      ref: master
  flutter_typeahead:
  uuid:
  geolocator: ^5.1.5
  modal_progress_hud: ^0.1.3
  fluttertoast: ^7.1.1
  iamport_flutter: ^0.9.13
  permission_handler: ^5.0.1+1
  extended_image: ^1.3.0
  kakao_flutter_sdk: ^0.5.2
  shared_preferences: ^0.5.12+4
  dio: ^3.0.9
  json_annotation: ^3.0.0
  package_info: ^0.4.0+2
  platform: ^2.2.1
  infinity_page_view: ^1.0.0
  sign_in_with_apple: ^2.5.4
  apple_sign_in: ^0.1.0
  flutter_easyloading: ^2.0.0
  email_validator: ^1.0.6
  location: ^3.2.4
  url_launcher : ^5.7.10
  geocoder: ^0.2.1
  flutter_spinkit: ^4.1.2
  transition: ^1.0.2
  keyboard_actions: ^3.3.1+1

  flutter_cache_manager: ^2.1.2
  image_gallery_saver: ^1.6.8
  audioplayers: ^0.15.1
  firebase_dynamic_links: ^0.6.3
  flutter_ringtone_player: ^2.0.0
  #구글 맵 마커클러스터링
  fluster: ^1.1.2
  local_assets_server: ^1.0.3+7
  #주소검색

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/newRoom/
    - assets/images/registration/
    - assets/images/splashScreen/
    - assets/images/loginScreen/
    - assets/images/dashBoardScreen/
    - assets/images/bottomNavigationImages/
    - assets/images/public/
    - assets/images/Map/
    - assets/images/dummy/
    - assets/images/mainReleaseRoomScreen/
    - assets/images/moreScreen/
    - assets/images/appTutorialScreen/
    - assets/images/releaseRoomScreen/
    - assets/images/LookForRoomsTutorial/
    - assets/images/Option/
    - assets/images/reviewScreenInMap/
    - assets/images/Chat/
    - assets/images/roomWannaLive/
    - assets/images/logo/
    - assets/images/GoogleMap/
    - assets/images/review/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
